export const FILE_SUBMITTED = 'FILE_SUBMITTED';
export const REMOVE_COMPLETED_UPLOAD = 'REMOVE_COMPLETED_UPLOAD';
export const UPLOAD_ERROR_OCCURRED = 'UPLOAD_ERROR_OCCURRED';
export const PERCENT_COMPLETED_UPDATED = 'PERCENT_COMPLETED_UPDATED';
export const UPLOAD_STATUS_UPDATED = 'UPLOAD_STATUS_UPDATED';
export const FILE_UPLOAD_COMPLETED = 'FILE_UPLOAD_COMPLETED';
