name: Node Setup & Yarn Install
description: 'Setup Node.js and install dependencies with Yarn'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Yarn cache
      uses: actions/cache@v4
      with:
        path: .yarn/cache
        key: yarn-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
        restore-keys: yarn-cache-

    - name: Install dependencies
      shell: bash
      run: corepack enable && yarn install
      env:
        # Use the local cache folder, so we can cache it above
        YARN_ENABLE_GLOBAL_CACHE: 'false'
