logFilters:
  # discard these messages that flood the build log
  - { code: YN0013, level: '${VERBOSE_YARN_LOG:-info}' } # fetching package
  - { code: YN0019, level: '${VERBOSE_YARN_LOG:-info}' } # unused cache entry
  # discard skipped build script message. We've explicitly disabled these for individual packages
  - { code: YN0005, level: discard }

packageExtensions:
  '@graphql-codegen/cli@*':
    peerDependencies:
      '@types/node': '*'
      'typescript': '*'
  '@graphql-codegen/named-operations-object@*':
    peerDependenciesMeta:
      # It doesn't actually use this peer dep
      graphql-tag: { optional: true }
  '@loadable/babel-plugin@*':
    peerDependencies:
      '@babel/helper-plugin-utils': '*'
  '@whatwg-node/fetch@*':
    peerDependenciesMeta:
      '@types/node': { optional: true }
  'ahooks@*':
    peerDependencies:
      '@babel/runtime': '*'
  'graphql-config@*':
    peerDependencies:
      '@types/node': '*'
      'typescript': '*'
  'react-editor-js@*':
    peerDependencies:
      react: '*'
      '@editorjs/editorjs': '*'
      '@editorjs/paragraph': '*'
  'razzle@*':
    peerDependencies:
      typescript: '*'
      '@babel/core': '*'
  'razzle-dev-utils@*':
    peerDependencies:
      typescript: '*'
  'react-pdf@*':
    peerDependenciesMeta:
      webpack: { optional: true }
