plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs

logFilters:
  # discard these messages that flood the build log
  - { code: YN0013, level: '${VERBOSE_YARN_LOG:-info}' } # fetching package
  - { code: YN0019, level: '${VERBOSE_YARN_LOG:-info}' } # unused cache entry
  # discard skipped build script message. We've explicitly disabled these for individual packages
  - { code: YN0005, level: discard }

packageExtensions:
  # awaiting fix: https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/issues/147
  '@endemolshinegroup/cosmiconfig-typescript-loader@*':
    peerDependenciesMeta:
      typescript: { optional: true }
  'razzle@*':
    peerDependencies:
      typescript: '*'
      '@babel/core': '*'
  'razzle-dev-utils@*':
    peerDependencies:
      typescript: '*'
  'react-pdf@*':
    peerDependenciesMeta:
      webpack: { optional: true }
  '@material-ui/pickers@*':
    dependencies:
      "@babel/runtime": "^7.17.8"
  'material-table@*':
    dependencies:
      "@babel/runtime": "^7.17.8"
  '@graphql-codegen/named-operations-object@*':
    peerDependenciesMeta:
      # It doesn't actually use this peer dep
      graphql-tag: { optional: true }
