FROM node:8

ENV CHROME_BIN /usr/bin/chromium

RUN set -ex; \
    mkdir -p /opt/build; \
    mkdir -p /opt/build/testResults; \
    \
    apt-get update && \
    DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y --no-install-recommends \
    chromium \
    libgconf-2-4 \
    openjdk-7-jre-headless \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/build

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

COPY docker/docker-entrypoint-tests.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint-tests.sh

VOLUME [/opt/build/testResults]

ENTRYPOINT ["docker-entrypoint-tests.sh"]
CMD yarn lint && yarn ng test --watch=false --browsers=docker --config karma.bamboo.conf.js --sourcemap --progress=false
