query PrayerStepList($engagement: ID!, $input: PostListInput) {
  engagement(id: $engagement) {
    ... on LanguageEngagement {
      id
      ...PostableId
      posts(input: $input) {
        canRead
        canCreate
        items {
          id
          type
          shareability
          effectiveShareability
          approvedShareability {
            value
            canEdit
          }
          body {
            value
          }
          report {
            value {
              id
            }
          }
          ...PostForm
        }
      }
    }
  }
}

mutation AttachPrayerToReport($input: UpdatePost!) {
  updatePost(input: $input) {
    post {
      id
      report {
        value {
          id
        }
      }
    }
  }
}

mutation ModeratePrayerRequest($input: ModeratePost!) {
  moderatePost(input: $input) {
    posts {
      id
      approvedShareability {
        value
        canEdit
      }
      effectiveShareability
    }
  }
}
