query PrayerStepList($engagement: ID!, $input: PostListInput) {
  engagement(id: $engagement) {
    ... on LanguageEngagement {
      id
      ...PostableId
      posts(input: $input) {
        canRead
        canCreate
        items {
          id
          type
          shareability
          effectiveShareability
          body {
            value
          }
          featured {
            value
          }
          report {
            canRead
            value {
              id
              start
              end
            }
          }
          ...PostForm
        }
      }
    }
  }
}

mutation AttachPrayerToReport($input: UpdatePost!) {
  updatePost(input: $input) {
    post {
      id
      report {
        value {
          id
        }
      }
    }
  }
}
