import { buildEnum } from '@app/core/models/enum';

export enum BibleBook {
  Genesis = 'gen',
  Exodus = 'exo',
  Leviticus = 'lev',
  Numbers = 'num',
  Deuteronomy = 'deu',
  Joshua = 'jos',
  Judges = 'jdg',
  Ruth = 'rut',
  FirstSamuel = '1sa',
  SecondSamuel = '2sa',
  FirstKings = '1ki',
  SecondKings = '2ki',
  FirstChronicles = '1ch',
  SecondChronicles = '2ch',
  Ezra = 'ezr',
  Nehemiah = 'neh',
  Esther = 'est',
  Job = 'job',
  Psalms = 'psa',
  Proverbs = 'pro',
  Ecclesiastes = 'ecc',
  SongOfSolomon = 'sng',
  Isaiah = 'isa',
  Jeremiah = 'jer',
  Lamentations = 'lam',
  Ezekiel = 'ezk',
  Daniel = 'dan',
  Hosea = 'hos',
  Joel = 'jol',
  Amos = 'amo',
  Obadiah = 'oba',
  Jonah = 'jon',
  Micah = 'mic',
  Nahum = 'nam',
  Habakkuk = 'hab',
  Zephaniah = 'zep',
  Haggai = 'hag',
  Zechariah = 'zec',
  Malachi = 'mal',

  Matthew = 'mat',
  Mark = 'mrk',
  Luke = 'luk',
  John = 'jhn',
  Acts = 'act',
  Romans = 'rom',
  FirstCorinthians = '1co',
  SecondCorinthians = '2co',
  Galatians = 'gal',
  Ephesians = 'eph',
  Philippians = 'php',
  Colossians = 'col',
  FirstThessalonians = '1th',
  SecondThessalonians = '2th',
  FirstTimothy = '1ti',
  SecondTimothy = '2ti',
  Titus = 'tit',
  Philemon = 'phm',
  Hebrews = 'heb',
  James = 'jas',
  FirstPeter = '1pe',
  SecondPeter = '2pe',
  FirstJohn = '1jn',
  SecondJohn = '2jn',
  ThirdJohn = '3jn',
  Jude = 'jud',
  Revelation = 'rev',
}

export namespace BibleBook {
  export const {entries, forUI, values, trackEntryBy, trackValueBy} = buildEnum(BibleBook, {
    [BibleBook.Genesis]: 'Genesis',
    [BibleBook.Exodus]: 'Exodus',
    [BibleBook.Leviticus]: 'Leviticus',
    [BibleBook.Numbers]: 'Numbers',
    [BibleBook.Deuteronomy]: 'Deuteronomy',
    [BibleBook.Joshua]: 'Joshua',
    [BibleBook.Judges]: 'Judges',
    [BibleBook.Ruth]: 'Ruth',
    [BibleBook.FirstSamuel]: '1 Samuel',
    [BibleBook.SecondSamuel]: '2 Samuel',
    [BibleBook.FirstKings]: '1 Kings',
    [BibleBook.SecondKings]: '2 Kings',
    [BibleBook.FirstChronicles]: '1 Chronicles',
    [BibleBook.SecondChronicles]: '2 Chronicles',
    [BibleBook.Ezra]: 'Ezra',
    [BibleBook.Nehemiah]: 'Nehemiah',
    [BibleBook.Esther]: 'Esther',
    [BibleBook.Job]: 'Job',
    [BibleBook.Psalms]: 'Psalms',
    [BibleBook.Proverbs]: 'Proverbs',
    [BibleBook.Ecclesiastes]: 'Ecclesiastes',
    [BibleBook.SongOfSolomon]: 'Song of Solomon',
    [BibleBook.Isaiah]: 'Isaiah',
    [BibleBook.Jeremiah]: 'Jeremiah',
    [BibleBook.Lamentations]: 'Lamentations',
    [BibleBook.Ezekiel]: 'Ezekiel',
    [BibleBook.Daniel]: 'Daniel',
    [BibleBook.Hosea]: 'Hosea',
    [BibleBook.Joel]: 'Joel',
    [BibleBook.Amos]: 'Amos',
    [BibleBook.Obadiah]: 'Obadiah',
    [BibleBook.Jonah]: 'Jonah',
    [BibleBook.Micah]: 'Micah',
    [BibleBook.Nahum]: 'Nahum',
    [BibleBook.Habakkuk]: 'Habakkuk',
    [BibleBook.Zephaniah]: 'Zephaniah',
    [BibleBook.Haggai]: 'Haggai',
    [BibleBook.Zechariah]: 'Zechariah',
    [BibleBook.Malachi]: 'Malachi',

    [BibleBook.Matthew]: 'Matthew',
    [BibleBook.Mark]: 'Mark',
    [BibleBook.Luke]: 'Luke',
    [BibleBook.John]: 'John',
    [BibleBook.Acts]: 'Acts',
    [BibleBook.Romans]: 'Romans',
    [BibleBook.FirstCorinthians]: '1 Corinthians',
    [BibleBook.SecondCorinthians]: '2 Corinthians',
    [BibleBook.Galatians]: 'Galatians',
    [BibleBook.Ephesians]: 'Ephesians',
    [BibleBook.Philippians]: 'Philippians',
    [BibleBook.Colossians]: 'Colossians',
    [BibleBook.FirstThessalonians]: '1 Thessalonians',
    [BibleBook.SecondThessalonians]: '2 Thessalonians',
    [BibleBook.FirstTimothy]: '1 Timothy',
    [BibleBook.SecondTimothy]: '2 Timothy',
    [BibleBook.Titus]: 'Titus',
    [BibleBook.Philemon]: 'Philemon',
    [BibleBook.Hebrews]: 'Hebrews',
    [BibleBook.James]: 'James',
    [BibleBook.FirstPeter]: '1 Peter',
    [BibleBook.SecondPeter]: '2 Peter',
    [BibleBook.FirstJohn]: '1 John',
    [BibleBook.SecondJohn]: '2 John',
    [BibleBook.ThirdJohn]: '3 John',
    [BibleBook.Jude]: 'Jude',
    [BibleBook.Revelation]: 'Revelation',
  });

  export const OldTestament = [
    BibleBook.Genesis,
    BibleBook.Exodus,
    BibleBook.Leviticus,
    BibleBook.Numbers,
    BibleBook.Deuteronomy,
    BibleBook.Joshua,
    BibleBook.Judges,
    BibleBook.Ruth,
    BibleBook.FirstSamuel,
    BibleBook.SecondSamuel,
    BibleBook.FirstKings,
    BibleBook.SecondKings,
    BibleBook.FirstChronicles,
    BibleBook.SecondChronicles,
    BibleBook.Ezra,
    BibleBook.Nehemiah,
    BibleBook.Esther,
    BibleBook.Job,
    BibleBook.Psalms,
    BibleBook.Proverbs,
    BibleBook.Ecclesiastes,
    BibleBook.SongOfSolomon,
    BibleBook.Isaiah,
    BibleBook.Jeremiah,
    BibleBook.Lamentations,
    BibleBook.Ezekiel,
    BibleBook.Daniel,
    BibleBook.Hosea,
    BibleBook.Joel,
    BibleBook.Amos,
    BibleBook.Obadiah,
    BibleBook.Jonah,
    BibleBook.Micah,
    BibleBook.Nahum,
    BibleBook.Habakkuk,
    BibleBook.Zephaniah,
    BibleBook.Haggai,
    BibleBook.Zechariah,
    BibleBook.Malachi,
  ];

  export const NewTestament = [
    BibleBook.Matthew,
    BibleBook.Mark,
    BibleBook.Luke,
    BibleBook.John,
    BibleBook.Acts,
    BibleBook.Romans,
    BibleBook.FirstCorinthians,
    BibleBook.SecondCorinthians,
    BibleBook.Galatians,
    BibleBook.Ephesians,
    BibleBook.Philippians,
    BibleBook.Colossians,
    BibleBook.FirstThessalonians,
    BibleBook.SecondThessalonians,
    BibleBook.FirstTimothy,
    BibleBook.SecondTimothy,
    BibleBook.Titus,
    BibleBook.Philemon,
    BibleBook.Hebrews,
    BibleBook.James,
    BibleBook.FirstPeter,
    BibleBook.SecondPeter,
    BibleBook.FirstJohn,
    BibleBook.SecondJohn,
    BibleBook.ThirdJohn,
    BibleBook.Jude,
    BibleBook.Revelation,
  ];

  export const Gospels = [
    BibleBook.Matthew,
    BibleBook.Mark,
    BibleBook.Luke,
    BibleBook.John,
  ];
}
