# Developer Note:
# These files are for the CI/CD system. The passwords used here are for testing purposes only and should only
# be used on systems that are not publicly accessible (i.e., behind an ACL of some sort). Each of these
# `ecs-*-compose.yml` files represents one of the deployment environments for the Bamboo CI/CD system.

version: '2'

services:
  cord-field:
    image: 103805181946.dkr.ecr.us-west-2.amazonaws.com/client/cord-field:${BAMBOO_BRANCH_TAG}
    ports: [ "80" ]
    env_file: .env
    environment:
      NG_BUILD_TARGET: uat
      SERVICE_80_NAME: client-tsco-cord-field-uat
    mem_limit: 256000000

  cord-api-plo:
    image: 103805181946.dkr.ecr.us-west-2.amazonaws.com/client/cord-api-plo:latest
    ports: [ "8001" ]
    environment:
      MONGO_DB_CONN: mongodb://cord-uat:0tnWj%5EoGNlf64Wwa2Fx%21@mongo-a.dev.olivetech.internal,mongo-b.dev.olivetech.internal,mongo-c.dev.olivetech.internal/cord-uat?replicaSet=dev
      NODE_ENV: uat
      CREATE_FAKE_USERS: "true"
      SERVICE_8001_NAME: client-tsco-cord-plo-uat
      MIGRATE: "true"
      DUMP_CONFIG: "true"
      DOMO: "false"
    mem_limit: 512000000

  profile-service:
    image: 103805181946.dkr.ecr.us-west-2.amazonaws.com/client/tsco-ilb-profile:latest
    ports: [ "8001" ]
    environment:
      MONGO_DB_CONN: mongodb://cord-uat-profile:0tnWj%5EoGNlf64Wwa2Fx%21@mongo-a.dev.olivetech.internal,mongo-b.dev.olivetech.internal,mongo-c.dev.olivetech.internal/cord-uat-profile?replicaSet=dev
      NODE_ENV: cord-uat
      ECHO_ENABLED: "true"
      BOOTSTRAP: "qa"
      SERVICE_8001_NAME: client-tsco-cord-profile-uat
    mem_limit: 256000000
