# Used for all local npm scripts/commands that require the full stack

version: '2'
services:

  cord-api-plo:
    image: 103805181946.dkr.ecr.us-west-2.amazonaws.com/client/cord-api-plo:latest
    ports:
        - 8002:8001
    links:
        - mongo-db
    environment:
      MONGO_DB_ADDRESS: mongo-db
      MONGO_DB_PORT: 27017
      NODE_ENV: docker
      MIGRATE: "true"
      DUMP_CONFIG: "true"
      CREATE_FAKE_USERS: "true"
      DOMO: "false"
    mem_limit: 256000000

  profile-service:
    image: 103805181946.dkr.ecr.us-west-2.amazonaws.com/client/tsco-ilb-profile:latest
    ports:
      - 8001:8001
    links:
      - mongo-db
    environment:
      MONGO_DB_ADDRESS: mongo-db
      MONGO_DB_PORT: 27017
      NODE_ENV: docker
      ECHO_ENABLED: "true"
      BOOTSTRAP: "qa"
      TRACE_REQ: "true"

  mongo-db:
    image: mongo
    ports:
      - 37001:27017
