version: '2'
services:

  local-test-service: # prefixed with "local-" to skip trying to pull image
    image: cord-field:tests
    volumes:
      - ../testResults:/opt/build/testResults
    links:
      - profile-service

  cord-api-plo:
    image: 103805181946.dkr.ecr.us-west-2.amazonaws.com/client/cord-api-plo:latest
    links:
        - mongo-db
    environment:
      MONGO_DB_ADDRESS: mongo-db
      MONGO_DB_PORT: 27017
      NODE_ENV: docker
      ECHO_ENABLED: "true"
      BOOTSTRAP: "qa"
      TRACE_REQ: "true"
      DUMP_CONFIG: "true"

  profile-service:
    image: 103805181946.dkr.ecr.us-west-2.amazonaws.com/client/tsco-ilb-profile:latest
    links:
      - mongo-db
    environment:
      MONGO_DB_ADDRESS: mongo-db
      MONGO_DB_PORT: 27017
      NODE_ENV: docker
      ECHO_ENABLED: "true"
      BOOTSTRAP: "qa"
      TRACE_REQ: "true"

  mongo-db:
    image: mongo
