# Used to verify that docker containers are built successfully

version: '2'
services:

  local-cord-field: # prefixed with "local-" to skip trying to pull image
    image: cord-field
    ports:
      - 4200:80

  cord-api-plo:
    image: 103805181946.dkr.ecr.us-west-2.amazonaws.com/client/cord-api-plo:latest
    ports:
        - "8001"
    links:
        - mongo-db
    environment:
      MONGO_DB_ADDRESS: mongo-db
      MONGO_DB_PORT: 27017
      NODE_ENV: dev
      MIGRATE: "true"
      DUMP_CONFIG: "true"
      DOMO: "false"
    mem_limit: 256000000

  ilb-profile-service:
    image: 103805181946.dkr.ecr.us-west-2.amazonaws.com/client/tsco-ilb-profile:latest
    ports:
      - 8001:8001
    links:
      - mongo-db
    environment:
      MONGO_DB_ADDRESS: mongo-db
      MONGO_DB_PORT: 27017
      NODE_ENV: docker

  mongo-db:
    image: mongo
    ports:
      - 37001:27017
