query ProgressReportDetail($id: ID!, $changesetId: ID) @live {
  periodicReport(id: $id, changeset: $changesetId) {
    ...ProgressReportDetail
  }
}

fragment ProgressReportDetail on ProgressReport {
  ...PeriodicReport
  parent {
    ...EngagementBreadcrumb
    ... on LanguageEngagement {
      posts(input: { count: 25, filter: { types: [Prayer] } }) {
        items {
          ...ProgressReportPrayerSummary
        }
      }
    }
  }
  status {
    value
  }
  cumulativeSummary {
    ...ProgressSummary
  }
  progress {
    ...ProgressOfProductForReport
  }
  pnpExtractionResult {
    ...pnpExtractionResult
  }
  teamNews {
    ...promptResponseList
  }
  communityStories {
    ...promptResponseList
  }
  otherActivities {
    ...promptResponseList
  }
  nextQuarterPlans {
    ...promptResponseList
  }
  media(input: { count: 100, sort: "createdAt", order: ASC }) {
    items {
      ...ProgressReportMediaSummary
    }
  }
  varianceExplanation {
    ...varianceExplanation
  }
  workflowEvents {
    ...workflowEvent
  }
}

fragment ProgressReportPrayerSummary on Post {
  id
  body {
    value
  }
  effectiveShareability
  featured {
    value
  }
  report {
    value {
      id
    }
  }
}

fragment ProgressReportMediaSummary on ProgressReportMedia {
  id
  variantGroup
  variant {
    key
  }
  media {
    __typename
    ... on Image {
      url
    }
  }
}

fragment ProgressSummary on ProgressSummary {
  actual
  planned
  variance
}

fragment ProgressOfProductForReport on ProductProgress {
  product {
    ...ProductInfoForProgressReport
  }
  report {
    ...Id
  }
  variant {
    ...variant
  }
  steps {
    step
    completed {
      canRead
      value
      canEdit
    }
  }
}

fragment ProductInfoForProgressReport on Product {
  ...Id
  label
  category
  steps {
    value
  }
  availableSteps
  progressStepMeasurement {
    value
  }
  progressTarget {
    value
  }
  ... on DirectScriptureProduct {
    scriptureReferences {
      value {
        ...Scripture
      }
    }
    unspecifiedScripture {
      value {
        book
      }
    }
  }
}
