export const GQLOperations = {
  Query: {
    Session: 'Session',
    Languages: 'Languages',
    Organization: 'Organization',
    Organizations: 'Organizations',
    ProjectPartnerships: 'ProjectPartnerships',
    ProjectList: 'ProjectList',
    ProjectOverview: 'ProjectOverview',
    User: 'User',
    Users: 'Users',
  },
  Mutation: {
    ForgotPassword: 'ForgotPassword',
    Login: 'Login',
    Logout: 'Logout',
    Register: 'Register',
    ResetPassword: 'ResetPassword',
    createLanguage: 'createLanguage',
    createOrganization: 'createOrganization',
    UpdateOrganization: 'UpdateOrganization',
    UpdatePartnership: 'UpdatePartnership',
    DeletePartnership: 'DeletePartnership',
    CreateProject: 'CreateProject',
    CreatePerson: 'CreatePerson',
  },
  Fragment: {
    DisplayLocation: 'DisplayLocation',
    DisplayCountry: 'DisplayCountry',
    DisplayRegion: 'DisplayRegion',
    DisplayZone: 'DisplayZone',
    DisplayPlace: 'DisplayPlace',
    BudgetOverview: 'BudgetOverview',
    InternshipEngagementListItem: 'InternshipEngagementListItem',
    LanguageEngagementListItem: 'LanguageEngagementListItem',
    LanguageListItem: 'LanguageListItem',
    OrganizationListItem: 'OrganizationListItem',
    PartnershipCard: 'PartnershipCard',
    PartnershipSummary: 'PartnershipSummary',
    PartnershipItem: 'PartnershipItem',
    ProjectListItem: 'ProjectListItem',
    ProjectMember: 'ProjectMember',
    ProjectMemberItem: 'ProjectMemberItem',
    ProjectMemberList: 'ProjectMemberList',
    LoggedInUser: 'LoggedInUser',
    UserListItem: 'UserListItem',
    orgDetails: 'orgDetails',
    EditPartnership: 'EditPartnership',
    userDetails: 'userDetails',
  },
};
