import type * as Types from '~/api/schema.graphql';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type BudgetCalculationFiscalYearFragment = (
  { readonly __typename?: 'BudgetCalculationFiscalYear' }
  & Pick<Types.BudgetCalculationFiscalYear, 'fiscalYear' | 'label' | 'cash' | 'inKind' | 'admin' | 'grandTotal' | 'totalCash' | 'otherPartnerContributions' | 'netToFunder' | 'adminFeeCap'>
);

export type BudgetCalculationTotalsFragment = (
  { readonly __typename?: 'BudgetCalculationTotals' }
  & Pick<Types.BudgetCalculationTotals, 'cash' | 'inKind' | 'admin' | 'grandTotal' | 'totalCash' | 'otherPartnerContributions' | 'netToFunder' | 'adminFeeCap'>
);

export type BudgetCalculationSummaryFragment = (
  { readonly __typename?: 'BudgetCalculationSummary' }
  & Pick<Types.BudgetCalculationSummary, 'bibleTranslationPercent' | 'funderBibleTranslationPercent' | 'costPerLanguage' | 'capped'>
  & { readonly totals: (
    { readonly __typename?: 'BudgetCalculationTotals' }
    & Pick<Types.BudgetCalculationTotals, 'cash' | 'inKind' | 'admin' | 'grandTotal' | 'totalCash' | 'otherPartnerContributions' | 'netToFunder' | 'adminFeeCap'>
  ), readonly fiscalYears: ReadonlyArray<(
    { readonly __typename?: 'BudgetCalculationFiscalYear' }
    & Pick<Types.BudgetCalculationFiscalYear, 'fiscalYear' | 'label' | 'cash' | 'inKind' | 'admin' | 'grandTotal' | 'totalCash' | 'otherPartnerContributions' | 'netToFunder' | 'adminFeeCap'>
  )> }
);

export const BudgetCalculationTotalsFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"BudgetCalculationTotals"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"BudgetCalculationTotals"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"cash"}},{"kind":"Field","name":{"kind":"Name","value":"inKind"}},{"kind":"Field","name":{"kind":"Name","value":"admin"}},{"kind":"Field","name":{"kind":"Name","value":"grandTotal"}},{"kind":"Field","name":{"kind":"Name","value":"totalCash"}},{"kind":"Field","name":{"kind":"Name","value":"otherPartnerContributions"}},{"kind":"Field","name":{"kind":"Name","value":"netToFunder"}},{"kind":"Field","name":{"kind":"Name","value":"adminFeeCap"}}]}}]} as unknown as DocumentNode<BudgetCalculationTotalsFragment, unknown>;
export const BudgetCalculationFiscalYearFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"BudgetCalculationFiscalYear"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"BudgetCalculationFiscalYear"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"fiscalYear"}},{"kind":"Field","name":{"kind":"Name","value":"label"}},{"kind":"Field","name":{"kind":"Name","value":"cash"}},{"kind":"Field","name":{"kind":"Name","value":"inKind"}},{"kind":"Field","name":{"kind":"Name","value":"admin"}},{"kind":"Field","name":{"kind":"Name","value":"grandTotal"}},{"kind":"Field","name":{"kind":"Name","value":"totalCash"}},{"kind":"Field","name":{"kind":"Name","value":"otherPartnerContributions"}},{"kind":"Field","name":{"kind":"Name","value":"netToFunder"}},{"kind":"Field","name":{"kind":"Name","value":"adminFeeCap"}}]}}]} as unknown as DocumentNode<BudgetCalculationFiscalYearFragment, unknown>;
export const BudgetCalculationSummaryFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"BudgetCalculationSummary"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"BudgetCalculationSummary"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"bibleTranslationPercent"}},{"kind":"Field","name":{"kind":"Name","value":"funderBibleTranslationPercent"}},{"kind":"Field","name":{"kind":"Name","value":"costPerLanguage"}},{"kind":"Field","name":{"kind":"Name","value":"capped"}},{"kind":"Field","name":{"kind":"Name","value":"totals"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"BudgetCalculationTotals"}}]}},{"kind":"Field","name":{"kind":"Name","value":"fiscalYears"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"BudgetCalculationFiscalYear"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"BudgetCalculationTotals"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"BudgetCalculationTotals"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"cash"}},{"kind":"Field","name":{"kind":"Name","value":"inKind"}},{"kind":"Field","name":{"kind":"Name","value":"admin"}},{"kind":"Field","name":{"kind":"Name","value":"grandTotal"}},{"kind":"Field","name":{"kind":"Name","value":"totalCash"}},{"kind":"Field","name":{"kind":"Name","value":"otherPartnerContributions"}},{"kind":"Field","name":{"kind":"Name","value":"netToFunder"}},{"kind":"Field","name":{"kind":"Name","value":"adminFeeCap"}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"BudgetCalculationFiscalYear"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"BudgetCalculationFiscalYear"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"fiscalYear"}},{"kind":"Field","name":{"kind":"Name","value":"label"}},{"kind":"Field","name":{"kind":"Name","value":"cash"}},{"kind":"Field","name":{"kind":"Name","value":"inKind"}},{"kind":"Field","name":{"kind":"Name","value":"admin"}},{"kind":"Field","name":{"kind":"Name","value":"grandTotal"}},{"kind":"Field","name":{"kind":"Name","value":"totalCash"}},{"kind":"Field","name":{"kind":"Name","value":"otherPartnerContributions"}},{"kind":"Field","name":{"kind":"Name","value":"netToFunder"}},{"kind":"Field","name":{"kind":"Name","value":"adminFeeCap"}}]}}]} as unknown as DocumentNode<BudgetCalculationSummaryFragment, unknown>;