name: Auto Add to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PROJECT: https://github.com/orgs/SeedCompany/projects/4

jobs:
  asdf:
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
      - name: Assign new issues to project backlog
        if: github.event == 'issue'
        uses: srggrs/assign-one-project-github-action@1.2.0
        with:
          project: ${{ env.PROJECT }}
          column_name: Project Backlog
      - name: Assign new pull requests to in progress
        if: github.event == 'issue'
        uses: srggrs/assign-one-project-github-action@1.2.0
        with:
          project: ${{ env.PROJECT }}
          column_name: In Progress
